server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: eureka
      roles: EUREKA_ADMIN

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defultZone: http://eureka:eureka@${eureka.instance.hostname}:${server.port}/eureka
