server:
  port: 8083

spring:
  application:
    name: spring-cloud-demo
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN
  boot:
    admin:
      client:
        username: admin #These two are needed so that the client
        password: admin #can register at the protected server api
  datasource:
    url: jdbc:mysql://mysql-service-address:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql123root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: test

eureka:
  instance:
#    hostname: eureka-service-address
#    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.hostname}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      user.name: ${spring.security.user.name}     #These two are needed so that the server
      user.password: ${spring.security.user.name} #can access the protected client endpoints
  client:
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://eureka:eureka@eureka-service-address:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

custom:
  log:
    additional-skip-pattern: /
    result: false

---
spring:
  profiles: test
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
custom:
  mybatisPlus:
    performance:
      enable: true
  swagger:
    csrf:
      enable: true

---
spring:
  profiles: prod

custom:
  swagger:
    enable: false
